### ISSUE TITLE
Support sending using RBF

### ISSUE THREAD

**Issue by jonathancross** [mycelium-com/wallet-android#350]
Hi all, it's been about 6 months since #173 was closed, so I thought it might be time to reconsider this feature request.

opt-in RBF is now supported in popular wallets like Electrum, GreenAddress, Bitcoin Core and the payment processor BitPay.

Why this would be nice _in addition to_ CPFP:
> Child Pays For Parent (CPFP) doesn’t solve the same problem. RBF allows the spender to increase fees; CPFP is useful because it allows the recipient to increase fees.

([Opt-in RBF FAQ](https://bitcoincore.org/en/faq/optin_rbf/))

For tx that originate from Mycelium, RBF can be significantly better than a CPFP bump as you don't need to pay for an entirely new transaction just to increase the fee on an old tx that isn't being mined.

**Comment by Giszmo** [comment]
If anybody wants to work on a merge request, this is what we had in mind (if I remember right):

* If anything but normal or priority fee is selected, the transaction will be marked RBF.
* The fee bumping button uses RBF if possible.
* Allow lower fees in the process.

**Comment by Perlover** [comment]
Hello, Mycelium developers!

I have idea about RBF
May be usefull

The wallet during process of signing transaction can generate 10 RBF transactions from minimal fee to prioroty fee. The Mycelium's interface can show min fee and max fee and preferable time for confirmation, for example 30min, 1 hour, 2 hour user. The user selects a time. After the wallet sends transaction with smallest fee. After 1/2 or 1/3 of preferable confirmation time wallet monitors this transaction and can send other transaction from 10 item set with more fee and so on. The pregeneration to be needed i think because PIN used for unblocking private keys so to generate RBF transactions after signing process will be problematic.

10 transaction will help to spend bitcoins with minimal fee. I think there in mempool is a war of fees. The big fee are there because many wallets generate high fee not accurate.

It's only idea. May be there some other problems, i don't know.

But i think now bitcoin mempool is so big because many wallets and users uses 2nd, 3rd unconfirmed transactions as CPFP. But this dirty mempool of bitcoin :(

**Comment by Giszmo** [comment]
the pre-signing of transactions is escpecially important for hardware wallet users and it will be a pain as long as those hardware wallets don't support batch signing. Also RBF will be a pain as soon as you do more than one transaction at a time that you bump independently ... but ... those transactions should get batched anyway, so it's more a pain for the developer :)

**Comment by Sjors** [comment]
Apologies for the noob question, but has RBF been implemented since, or this indeed still open?

**Comment by jonathancross** [comment]
@sergeylappo is RBF support being implemented?

**Comment by Giszmo** [comment]
We are currently not working on RBF and neither has it been implemented.

**Comment by Sjors** [comment]
@Giszmo got it, thanks for the info!

**Comment by Hitgub01** [comment]
Recovery tool BTC, Hi all when i wan't to use the recovery tool i get an error about a string..., can someone help me please

**Comment by jonathancross** [comment]
> Recovery tool BTC, Hi all when i wan't to use the recovery tool i get an error about a string..., can someone help me please

Sorry, but this is the wrong place for that question. It has nothing to do with this issue.
