### ISSUE TITLE
Show nearby OpenStreetmap Bitcoin nodes

### ISSUE THREAD

**Issue by seanlynch** [mycelium-com/wallet-android#43]
I believe the tag to look for is payment:bitcoin=yes, but there may be others. This would both encourage putting Bitcoin locations into OSM and make it easier to find places to spend or get Bitcoin.

**Comment by Giszmo** [comment]
I don't share the security concerns. A webview inside an app should not have easy access to stuff outside the webview. Apart from this I would prefer to simply open the browser. Sure, not all new bitcoin users know coinmap (or whichever other provider we may endorse since coinmap.org moved away from using OSM), so adding a button "show nearby venues" that opens the browser would be helpful for new users.

**Comment by Giszmo** [comment]
Old old issue and already kind of obsolete when last commented :(
