### ISSUE TITLE
How does the Master Seed Verification work?

### ISSUE THREAD

**Issue by rraallvv** [mycelium-com/wallet-android#457]
After I'm presented with the whole sequence of words to write down, I'm prompted to type the words, the problem is that there is no way to indicate when a word has been fully entered.

I tried to take a screenshot to check whether it could be a problem with the keyboard layout being occluded by the soft keys, but it didn't work. Is the screenshot capability disable for this app?

Since I couldn't take a screenshot, I'm describing how the keyboard looks:

It's the English QWERTY keyboard with only letters, and no numbers, only there is one additional key for backspace.

**Comment by Giszmo** [comment]
I assume it is a usability issue only. While you type, you get words suggested from the allowed 2048 english words. When you chose one of them or finish typing one, you get to the next word. If you type a word, "or" for example and find no way to skip to the next word, then that is because "or" is not an allowed word. All allowed words have at least 3 letters and you need at most 4 letters to know which one of the 2048 it is. Type "moth" and you get proposed only one word: "mother". So in your backup you are good with 4 letters per word.

**Comment by Giszmo** [comment]
Closing now, assuming this was it. If not, feel free to re-open/comment again.

**Comment by rraallvv** [comment]
@Giszmo is there some other place to ask questions related to usability issues? Thanks.
