### ISSUE TITLE
Bump Fee should allow to set the amount to bump

### ISSUE THREAD

**Issue by MarkusTeufelberger** [mycelium-com/wallet-android#469]
Currently there's only a dialog box that tells me that it would bump to a certain amount and I can't modify that number - only accept or cancel.

**Comment by dscotese** [comment]
In /mbw/src/main/java/com/mycelium/wallet/activity/main/TransactionHistoryFragment.java there is the function onPostExecute which chooses a fee ("getHigh()") and then submits it to tryCreateBumpTransaction which returns null or an unsigned transaction.  It then presents a dialog to the user to approve the bumping of the fee.  That dialog could have an option to add or subtract 5 sats/vB (or some sats/vByte set under settings as "BumpFee Delta") to the proposed new fee, so that if it is selected, tryCreateBumpTransaction would be called again with the new, higher or lower fee and the user could keep adjusting it until their preferred "otherwise unavailable fee" was chosen.  This is a sloppy but quick and effective way to address this issue.

**Comment by Giszmo** [comment]
The bump fee feature is in some cases a last resort and most user do not understand how fees or unconfirmed transactions work. Our current implementation only takes the direct prior transaction into account even if there is already a chain of unconfirmed transactions that built up. Miners don't look for infinite chains but cut off after 10 or so, so if the bump transaction is # 11, it will just not get considered. The user has no room to play cheap and no reason to over-pay on the high priority.

The room to play with non-top-priority fees would be given if we had the means to check the full cluster of unconfirmed transactions and/or if the bump transaction were RBF which we neither support so far.

Yes, CPFP could and should be improved but with RBF it will work vastly different anyway. I'll close this for now.

**Comment by MarkusTeufelberger** [comment]
I just wanted to be able to set the amount in that dialog box manually, nothing more. :-(

**Comment by Giszmo** [comment]
I'm sorry. For you (and me personally) this would be the right thing to have but Mycelium would need an expert mode for that or else such a feature would do more harm than good.
