### ISSUE TITLE
Android Studio Build Failed

### ISSUE THREAD

**Issue by Huihh** [mycelium-com/wallet-android#485]
I clone latest version,  Used Android Studio3.2.1 buid project, but occure Error：
     "Unable to find a matching configuration of project :bitcoincashj:core: None of the consumable configurations have attributes. "

what should  I do,   Many Thanks

**Comment by Vutov** [comment]
I have probably similar issue (not sure), but its failing build related as well so I hope you don't mind me raising it here - `Unable to resolve dependency for ':mbw@prodnetReleaseUnitTest/compileClasspath': Could not resolve project :modulespvcontract.` and a few others with the same error. It happens when I try to build master branch. Using latest Android Studio.

**Comment by sergeylappo** [comment]
Did you try to use `git submodule init` and then `git submodule update`?

**Comment by Huihh** [comment]
> Did you try to use `git submodule init` and then `git submodule update`?

Thank you very much
