### ISSUE TITLE
Unable to get version update prompt

### ISSUE THREAD

**Issue by tonneymilk** [mycelium-com/wallet-android#517]
The version number I currently use is 3.0. 0.15. At the current version, click the "check for update", and the system prompts the "Unable to receive version information". What's the cause, please? I look forward to your reply.

**Comment by Giszmo** [comment]
This is probably a bug due to not all servers knowing about version upgrades and you are connected to the wrong one. Restarting the app should resolve the issue. Of course we should deploy update information to all servers and not only to one. One usually does the trick to get users to update as it randomly triggers an update notification but for when you explicitly want to know if there is an update, it is not good enough.

**Comment by Giszmo** [comment]
Version 3.0.0.15 is almost 2 years old. Yes, please update. And also please always update before creating bug reports. I assume the issue is fixed.

```
$ git show v3.0.0.15
commit d4e66788312cfe821d3827c4a3af6c83a78ea4a8 (tag: v3.0.0.15)
Merge: a3a87f35c bb3b702ee
Author: Sergey Dolgopolov <itserg2008@gmail.com>
Date:   Tue Jul 30 09:29:56 2019 +0300

    Merge pull request #1223 from mycelium-com/release3000015
    
    versionCode 3000015
```
