### ISSUE TITLE
BNB transfer to the BTC did not receive money SCAM

### ISSUE THREAD

**Issue by Zorin1402** [mycelium-com/wallet-android#526]
I have a mobile wallet mycelium 11/19/2019 brought 8 bnb to it, there is an automatic conversion to BTC, as I said, yesterday there was a conclusion, the money arrived but not converted, as I have, I really hope for your help
Адрес:bnb1z48pp6kvlcrqe8vcucqpggeh60ngxmzklkzfm0	
 Txid: EBC4BCB064C13986E82A67238341C5F4AE49E47BB0F7186F918773F1C38D3B31
https://explorer.binance.org/tx/EBC4BCB064C13986E82A67238341C5F4AE49E47BB0F7186F918773F1C38D3B31
I wrote here there is no answer from them support@mycelium.com I hope you can help me somehow resolve the issue

**Comment by agneslovelace** [comment]
so you have used "Shift any coins to BTC" on the Balance tab? This service is provided by Changelly and not Mycelium, so please report the issue to their support https://support.changelly.com/support/home

**Comment by agneslovelace** [comment]
I think the probability of scam is low as Changelly exists for quite a long time and has many users. It's probably some delays or other reasons of technical character.

**Comment by Zorin1402** [comment]
I really hope to get my bitcoins, thank you friend

**Comment by Zorin1402** [comment]
the question is still open, the money has not arrived

**Comment by agneslovelace** [comment]
Have you contacted https://support.changelly.com/support/home?

**Comment by Zorin1402** [comment]
yes of course, but so far there is no answer, therefore I consider the question open, I can provide correspondence

**Comment by changelly** [comment]
Hello! Please accept our apologies for the delay. The transaction got failed due to the required MEMO missing. We've already received all the necessary information from you and the Mycelium wallet in order to process your transaction further so it should be completed shortly. Once it's completed, our support team will contact you and provide with the transaction hash.

**Comment by Zorin1402** [comment]
I have heard your promises for 11 days, no action from you, no money from you

**Comment by changelly** [comment]
Hello! Your transaction is completed. Here is the hash. https://www.blockchain.com/btc/tx/c88fca2c9817c01c465aa3f7b154e7f6e0f11de6c8b35348bb22831aea4d1fb6.
Our team is concerned about the fact that you had an unfortunate experience with us. As Changelly has always been a client-oriented service, we are making all in our power to make the experience of every customer the most seamless and effortless so that you would benefit from the best trading conditions available. Please specify your email in Changelly Facebook DM so we could reach you out and suggest the special offer.

**Comment by Zorin1402** [comment]
я получил меньше указанной суммы ! Dear Customer,

You're to receive around 0.01625 BTC.


вт, 3 дек. 2019 г. в 16:08, changelly <notifications@github.com>:

**Comment by Zorin1402** [comment]
да и пофигу, главное я надеюсь больше не будет у вас этих проблемп


вт, 3 дек. 2019 г. в 16:21, Z - Studio <zorin1402@gmail.com>:

**Comment by changelly** [comment]
We are sorry for the delay and will do everything in our power to eliminate such issues in the future and speed up the processes. As it was stated in the support chat, you would receive around 0.01625 BTC. The discrepancy occurred (0.0000915 BTC) lies in the fact of cryptocurrency fluctuation which is beyond our control, unfortunately.

If you have any questions for Changelly, please don't hesitate to shoot us a note at support@changelly.com. We are always ready to help you out!

**Comment by Hitgub01** [comment]
How can i move the amount that is nog disposable to my wallet.Op 3 dec. 2019 18:48 schreef changelly <notifications@github.com>:We are sorry for the delay and will do everything in our power to eliminate such issues in the future and speed up the processes. As it was stated in the support chat, you would receive around 0.01625 BTC. The discrepancy occurred (0.0000915 BTC) lies in the fact of cryptocurrency fluctuation which is beyond our control, unfortunately.
If you have any questions for Changelly, please don't hesitate to shoot us a note at support@changelly.com. We are always ready to help you out!
