### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by sergeylappo** [mycelium-com/wallet-android#551]
Steps to reproduce:

1. Clone project
2. git submodule update --init --recursive
3. /gradlew build

Failed with:
> Task :mbwlib:test FAILED

com.mycelium.paymentrequest.PaymentRequestInformationTest > testFromRawPaymentRequestSig FAILED
    java.io.FileNotFoundException at PaymentRequestInformationTest.java:45

com.mycelium.paymentrequest.PaymentRequestInformationTest > testFromRawPaymentRequestNoSig FAILED
    java.io.FileNotFoundException at PaymentRequestInformationTest.java:45

28 tests completed, 2 failed

**Comment by Giszmo** [comment]
What is it you are trying to achieve. The [build instructions](https://github.com/mycelium-com/wallet-android#building) for the wallet are:

```
git clone https://github.com/mycelium-com/wallet-android.git
cd wallet-android
git clone https://github.com/mycelium-com/wallet-android-modularization-tools.git
git submodule update --init --recursive
./gradlew clean test mbw::asProdRel mbw::asBtRel
```

and those do work.

As of e8fae64752ee2eef6fa6149c85a7592294083f17, `./gradlew buil` also fails but not due to unit tests. I tend to file this as a low priority bug.
