### ISSUE TITLE
Tansaction not sending

### ISSUE THREAD

**Issue by freerangemom** [mycelium-com/wallet-android#582]
How do I reverse a transaction? Its been hanging for 3 weeks now. (I'm a noob... sent a small amount with a small transaction fee.)

**Comment by tgbv** [comment]
If issue is still relevant, due to how bitcoin works you can't reverse transactions. Mycelium can help you rebroadcast the transaction in case some miners lost it from their mempool, or bump the fee (CPFP - https://bitcoinops.org/en/topics/cpfp/) in hope some miners will mine your ancestor transaction.

**Comment by Giszmo** [comment]
You would usually reload the account, so that the Mycelium client also forgets about it and you can spend the funds otherwise. To do so, go to the accounts list, select the affected account and in the context menu "Reload Account".
